/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Query_KeyValuePair {
    char key[1024];
    int32_t valueType;
    int64_t valueInt;
    float valueReal;
    char valueString[1024];
} Query_KeyValuePair;

typedef struct _Query_ValueSetting {
    Query_KeyValuePair kv;
} Query_ValueSetting;

typedef struct _Query_Comparator {
    int32_t operation;
    Query_KeyValuePair kv;
} Query_Comparator;

typedef struct _Query_Filter {
    pb_size_t compList_count;
    Query_Comparator compList[20];
} Query_Filter;

typedef struct _Query {
    int32_t command;
    pb_size_t filtersList_count;
    Query_Filter filtersList[20];
    pb_size_t settingsList_count;
    Query_ValueSetting settingsList[20];
} Query;

typedef struct _Response {
    char rString[1024];
    int32_t last;
} Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Query_init_default                       {0, 0, {Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default, Query_Filter_init_default}, 0, {Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default, Query_ValueSetting_init_default}}
#define Query_Filter_init_default                {0, {Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default, Query_Comparator_init_default}}
#define Query_ValueSetting_init_default          {Query_KeyValuePair_init_default}
#define Query_Comparator_init_default            {0, Query_KeyValuePair_init_default}
#define Query_KeyValuePair_init_default          {"", 0, 0, 0, ""}
#define Response_init_default                    {"", 0}
#define Query_init_zero                          {0, 0, {Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero, Query_Filter_init_zero}, 0, {Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero, Query_ValueSetting_init_zero}}
#define Query_Filter_init_zero                   {0, {Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero, Query_Comparator_init_zero}}
#define Query_ValueSetting_init_zero             {Query_KeyValuePair_init_zero}
#define Query_Comparator_init_zero               {0, Query_KeyValuePair_init_zero}
#define Query_KeyValuePair_init_zero             {"", 0, 0, 0, ""}
#define Response_init_zero                       {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define Query_KeyValuePair_key_tag               1
#define Query_KeyValuePair_valueType_tag         2
#define Query_KeyValuePair_valueInt_tag          3
#define Query_KeyValuePair_valueReal_tag         4
#define Query_KeyValuePair_valueString_tag       5
#define Query_ValueSetting_kv_tag                1
#define Query_Comparator_operation_tag           1
#define Query_Comparator_kv_tag                  2
#define Query_Filter_compList_tag                1
#define Query_command_tag                        1
#define Query_filtersList_tag                    2
#define Query_settingsList_tag                   3
#define Response_rString_tag                     1
#define Response_last_tag                        2

/* Struct field encoding specification for nanopb */
#define Query_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    command,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  filtersList,       2) \
X(a, STATIC,   REPEATED, MESSAGE,  settingsList,      3)
#define Query_CALLBACK NULL
#define Query_DEFAULT NULL
#define Query_filtersList_MSGTYPE Query_Filter
#define Query_settingsList_MSGTYPE Query_ValueSetting

#define Query_Filter_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  compList,          1)
#define Query_Filter_CALLBACK NULL
#define Query_Filter_DEFAULT NULL
#define Query_Filter_compList_MSGTYPE Query_Comparator

#define Query_ValueSetting_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  kv,                1)
#define Query_ValueSetting_CALLBACK NULL
#define Query_ValueSetting_DEFAULT NULL
#define Query_ValueSetting_kv_MSGTYPE Query_KeyValuePair

#define Query_Comparator_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    operation,         1) \
X(a, STATIC,   REQUIRED, MESSAGE,  kv,                2)
#define Query_Comparator_CALLBACK NULL
#define Query_Comparator_DEFAULT NULL
#define Query_Comparator_kv_MSGTYPE Query_KeyValuePair

#define Query_KeyValuePair_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   key,               1) \
X(a, STATIC,   REQUIRED, INT32,    valueType,         2) \
X(a, STATIC,   REQUIRED, INT64,    valueInt,          3) \
X(a, STATIC,   REQUIRED, FLOAT,    valueReal,         4) \
X(a, STATIC,   REQUIRED, STRING,   valueString,       5)
#define Query_KeyValuePair_CALLBACK NULL
#define Query_KeyValuePair_DEFAULT NULL

#define Response_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   rString,           1) \
X(a, STATIC,   REQUIRED, INT32,    last,              2)
#define Response_CALLBACK NULL
#define Response_DEFAULT NULL

extern const pb_msgdesc_t Query_msg;
extern const pb_msgdesc_t Query_Filter_msg;
extern const pb_msgdesc_t Query_ValueSetting_msg;
extern const pb_msgdesc_t Query_Comparator_msg;
extern const pb_msgdesc_t Query_KeyValuePair_msg;
extern const pb_msgdesc_t Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Query_fields &Query_msg
#define Query_Filter_fields &Query_Filter_msg
#define Query_ValueSetting_fields &Query_ValueSetting_msg
#define Query_Comparator_fields &Query_Comparator_msg
#define Query_KeyValuePair_fields &Query_KeyValuePair_msg
#define Response_fields &Response_msg

/* Maximum encoded size of messages (where known) */
#define Query_Comparator_size                    2093
#define Query_Filter_size                        41920
#define Query_KeyValuePair_size                  2079
#define Query_ValueSetting_size                  2082
#define Query_size                               880191
#define Response_size                            1037

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
