/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: Query */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: Query
#endif
PB_BIND(Query, Query, 4)


PB_BIND(Query_Filter, Query_Filter, 4)


PB_BIND(Query_ValueSetting, Query_ValueSetting, 2)


PB_BIND(Query_Comparator, Query_Comparator, 2)


PB_BIND(Query_KeyValuePair, Query_KeyValuePair, 2)


PB_BIND(Response, Response, 2)



